# Generated by Django 5.0.2 on 2024-02-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventDescription',
            field=models.TextField(default=''),
        ),
    ]
